base_url = "https://litflixinfo.pages.dev"
title = "Litflix by Spinoza Entertainment"

compile_sass = true

highlight_code = true

build_search_index = false

check_external_links = true

taxonomies = [
    { name = "tags", rss = true },
    { name = "authors", rss = true }
]

[extra]
show_word_count = true
show_reading_time = true

date_format = "%a %b %e, %Y"

home = "home"

sam_menu = [
    { text = "litflix main page", link = "https://litflix.spinoza.dedyn.io" },
    { text = "request movies and shows", link = "https://requests.spinoza.dedyn.io" },
    { text = "tutorial", link = "/tutorial" },
    { text = "connect with us", link = "https://simplex.chat/contact#/?v=1-4&smp=smp%3A%2F%2FenEkec4hlR3UtKx2NMpOUK_K4ZuDxjWBO1d9Y4YXVaA%3D%40smp14.simplex.im%2FJKvIFIDXZYlYV0vO6GB0KVZagna2AzYn%23%2F%3Fv%3D1-2%26dh%3DMCowBQYDK2VuAyEADAh0O9-hAlGUV2ged_gNlOYM497JkdT3sKJz0Gcjpw4%253D%26srv%3Daspkyu2sopsnizbyfabtsicikr2s4r3ti35jogbcekhm3fsoeyjvgrid.onion&data=%7B%22type%22%3A%22group%22%2C%22groupLinkId%22%3A%22Y5ZmKtjzTatc3Tgv8AWIkA%3D%3D%22%7D" }

]

sam_bottom_menu = true

[extra.sam_footer]
text = "i do not know how to teach philosophy without becoming a disturber of the peace"
